platform :ios, '9.3'

target 'FADemo' do
  use_frameworks!
  inhibit_all_warnings!

  # Pods for FADemo
  pod 'Firebase/Core'
  pod 'BaseTracking', :git => 'https://github.com/limadeveloper/BaseTracking.git', :branch => 'master'

end