platform :ios, '9.3'

target 'GADemo' do
  use_frameworks!
  inhibit_all_warnings!

  # Pods for GADemo
  pod 'GoogleAnalytics'
  pod 'BaseTracking', :git => 'https://github.com/limadeveloper/BaseTracking.git', :branch => 'master'

end