platform :ios, '12.1'

target 'GADemo' do
  use_frameworks!
  inhibit_all_warnings!

  # Pods for GADemo
  pod 'GoogleAnalytics'
  pod 'BaseTracking', :path => '../../'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end
